version: '2'
services:
  server:
    build:
        context: .
        dockerfile: build/nginx/Dockerfile
    ports:
     - "3030:80"
    volumes:
     - .:/var/www/html
    networks:
     - acmepodcast
  fpm:
    build:
        context: .
        dockerfile: build/fpm/Dockerfile
    volumes:
     - .:/var/www/html
    networks:
     - acmepodcast
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: acmepodcast
      MYSQL_USER: acmepodcast
      MYSQL_PASSWORD: secret
    volumes:
     - ./database:/var/lib/mysql
    networks:
     - acmepodcast
networks:
  acmepodcast:
    driver: "bridge"
volumes:
  data:
    driver: "local"
