version: '2'
services:
  server:
    build:
        context: .
        dockerfile: build/nginx/Dockerfile
    ports:
     - "3030:80"
    volumes:
     - .:/var/www/html
    networks:
     - acmepodcast
  fpm:
    build:
        context: .
        dockerfile: build/fpm/Dockerfile
    volumes:
     - .:/var/www/html
    networks:
     - acmepodcast
networks:
  acmepodcast:
    driver: "bridge"
volumes:
  data:
    driver: "local"
